
name: Build and Deploy Development
on:
  push:
    branches:
    - "development"
    workflow_dispatch:

jobs:
  build-development:
    name: Build Development
    strategy:
      fail-fast: true
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64, arm64]
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
      - uses: actions/setup-go@v3

      - name: Generate version strings and frontend
        run: go generate ./...
      
      - name: Build
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: go build -o ./build
          
      - name: Compress
        run: zip ./build/fntwo-${{ matrix.os }}-${{ matrix.arch }}.zip ./build/fntwo
          
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: development-artifacts
          path: |
            ./build/fntwo-${{ matrix.os }}-${{ matrix.arch }}.zip
      
  deploy-development:
    needs: build-development
    name: Deploy Development
    steps:
      - name: Download Artifact
        uses: "actions/download-artifact@v3"
        with:
          name: development-artifacts
          path: bruh
      
      - name: Display structure of downloaded files
        run: ls -alh
        working-directory: bruh
